{
 "title": "VoltDB Topics",
 "tags": [
  "voltdb",
  "topics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},topic_name)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\",topic_name=~\"$topic\"}, partition_id)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of topics",
   "type": "stat",
   "description": "Informational metric with topic metadata. Tags: TOPIC_STATUS - \"Stable\" - The queue is complete; \"Backfilling\" - records are missing but are being retrieved from other servers; \"Blocked\" - records are missing from all copies of the partition; \"Orphaned\" - the queue is no longer being served by this partition, but is saved in case other copies of the queue are blocked or backfilling and need the data. This is a transitional state and the queue is deleted as soon as no other copies need its records. TOPIC_RETENTION_POLICY - The retention policy for this topic. TOPIC_IS_MASTER - \"True\" or \"False\" indicating whether the current site is the master for the logical partition.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic_name) (voltdb_topic_info{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest message received",
   "type": "stat",
   "description": "The timestamp when the most recent message (the last offset) was inserted into the queue.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (voltdb_topic_last_offset_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\"} *1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic statuses",
   "type": "piechart",
   "description": "Informational metric with topic metadata. Tags: TOPIC_STATUS - \"Stable\" - The queue is complete; \"Backfilling\" - records are missing but are being retrieved from other servers; \"Blocked\" - records are missing from all copies of the partition; \"Orphaned\" - the queue is no longer being served by this partition, but is saved in case other copies of the queue are blocked or backfilling and need the data. This is a transitional state and the queue is deleted as soon as no other copies need its records. TOPIC_RETENTION_POLICY - The retention policy for this topic. TOPIC_IS_MASTER - \"True\" or \"False\" indicating whether the current site is the master for the logical partition.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count by(topic_status) (voltdb_topic_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\", topic_status=\"STABLE\"})",
     "legendFormat": "{{topic_status}}"
    },
    {
     "expr": "count by(topic_status) (voltdb_topic_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\", topic_status=\"BLOCKED\"})",
     "legendFormat": "{{topic_status}}"
    },
    {
     "expr": "count by(topic_status) (voltdb_topic_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\", topic_status=\"BACKFILLING\"})",
     "legendFormat": "{{topic_status}}"
    },
    {
     "expr": "count by(topic_status) (voltdb_topic_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\", topic_status=\"ORPHANED\"})",
     "legendFormat": "{{topic_status}}"
    }
   ]
  },
  {
   "title": "Rate of bytes fetched",
   "type": "stat",
   "description": "The size of data sent to consumers for this partition and topic.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_topic_bytes_fetched_bytes{namespace=\"$cluster\",host_name=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occupied disk space",
   "type": "stat",
   "description": "The size of data stored on disk for this partition and topic.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_topic_bytes_on_disk_bytes{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming messages rate",
   "type": "stat",
   "description": "The value of the last offset in the topic.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_topic_last_offset{namespace=\"$cluster\",host_name=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topics summary ($topic)",
   "type": "table",
   "description": "Informational metric with topic metadata. Tags: TOPIC_STATUS - \"Stable\" - The queue is complete; \"Backfilling\" - records are missing but are being retrieved from other servers; \"Blocked\" - records are missing from all copies of the partition; \"Orphaned\" - the queue is no longer being served by this partition, but is saved in case other copies of the queue are blocked or backfilling and need the data. This is a transitional state and the queue is deleted as soon as no other copies need its records. TOPIC_RETENTION_POLICY - The retention policy for this topic. TOPIC_IS_MASTER - \"True\" or \"False\" indicating whether the current site is the master for the logical partition.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "voltdb_topic_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Topic state ($topic)",
   "type": "state-timeline",
   "description": "Informational metric with topic metadata. Tags: TOPIC_STATUS - \"Stable\" - The queue is complete; \"Backfilling\" - records are missing but are being retrieved from other servers; \"Blocked\" - records are missing from all copies of the partition; \"Orphaned\" - the queue is no longer being served by this partition, but is saved in case other copies of the queue are blocked or backfilling and need the data. This is a transitional state and the queue is deleted as soon as no other copies need its records. TOPIC_RETENTION_POLICY - The retention policy for this topic. TOPIC_IS_MASTER - \"True\" or \"False\" indicating whether the current site is the master for the logical partition.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "repeat": "topic",
   "targets": [
    {
     "expr": "sum by(partition_id, topic_name, topic_status) (voltdb_topic_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Topic writers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lastest write",
   "type": "timeseries",
   "description": "The timestamp when the most recent message (the last offset) was inserted into the queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "max by (topic_name) (voltdb_topic_last_offset_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}) * 1000",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Incoming messages rate",
   "type": "timeseries",
   "description": "The value of the last offset in the topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(topic_name)(rate(voltdb_topic_last_offset{namespace=\"$cluster\", host_name=~\"$host\", partition_id=~\"$partition\", topic_name=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Last offset and timestamp",
   "type": "timeseries",
   "description": "- `voltdb_topic_last_offset`: The value of the last offset in the topic.\n- `voltdb_topic_last_offset_timestamp_seconds`: The timestamp when the most recent message (the last offset) was inserted into the queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "voltdb_topic_last_offset{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}",
     "legendFormat": "last offset (host - {{host_name}}, partition - {{partition_id}}, topic - {{topic_name}})"
    },
    {
     "expr": "voltdb_topic_last_offset_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"} *1000",
     "legendFormat": "last offset timestamp (host - {{host_name}}, partition - {{partition_id}}, topic - {{topic_name}})"
    }
   ]
  },
  {
   "title": "First offset and timestamp",
   "type": "timeseries",
   "description": "- `voltdb_topic_first_offset`: The value of the first offset currently available in the topic.\n- `voltdb_topic_first_offset_timestamp_seconds`: The timestamp when the first offset was inserted into the queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_topic_first_offset{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}",
     "legendFormat": "first offset (host - {{host_name}}, partition - {{partition_id}}, topic - {{topic_name}})"
    },
    {
     "expr": "voltdb_topic_first_offset_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"} *1000",
     "legendFormat": "first offset timestamp (host - {{host_name}}, partition - {{partition_id}}, topic - {{topic_name}})"
    }
   ]
  },
  {
   "title": "Topic readers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of bytes fetched from topic",
   "type": "timeseries",
   "description": "The size of data sent to consumers for this partition and topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (topic_name) (rate(voltdb_topic_bytes_fetched_bytes{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "bytes fetched for topic {{topic_name}}"
    }
   ]
  },
  {
   "title": "Rate of skipped rows from topic-partition",
   "type": "timeseries",
   "description": "The number of skipped rows that otherwise would cause an error. Only applies if the topic's option consumer.skip.errors is true.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(voltdb_topic_skipped_rows_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}[$__rate_interval])",
     "legendFormat": "skipped rows (host - {{host_name}}, partition - {{partition_id}}, topic - {{topic_name}})"
    }
   ]
  },
  {
   "title": "Rate of bytes fetched from topic-partition",
   "type": "timeseries",
   "description": "The size of data sent to consumers for this partition and topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(voltdb_topic_bytes_fetched_bytes{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}[$__rate_interval])",
     "legendFormat": "bytes fetched (host - {{host_name}}, partition - {{partition_id}}, topic - {{topic_name}})"
    }
   ]
  },
  {
   "title": "Rate of skipped row from topic",
   "type": "timeseries",
   "description": "The number of skipped rows that otherwise would cause an error. Only applies if the topic's option consumer.skip.errors is true.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic_name) (rate(voltdb_topic_skipped_rows_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "skipped rows for topic {{topic_name}}"
    }
   ]
  },
  {
   "title": "Offset on which a consumer error occured",
   "type": "timeseries",
   "description": "If an error occurs while encoding a message for consumers, an error is returned to the consumer, the offset of the message is recoded here.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "voltdb_topic_error_offset{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",topic_name=~\"$topic\"}",
     "legendFormat": "error offset (host - {{host_name}}, partition - {{partition_id}}, topic - {{topic_name}})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes on disk per topic",
   "type": "timeseries",
   "description": "The size of data stored on disk for this partition and topic.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic_name) (voltdb_topic_bytes_on_disk_bytes{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\", topic_name=~\"$topic\"})",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Bytes on disk per topic partition",
   "type": "marcusolsson-treemap-panel",
   "description": "The size of data stored on disk for this partition and topic.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (partition_id, topic_name) (voltdb_topic_bytes_on_disk_bytes{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\", topic_name=~\"$topic\"})"
    }
   ]
  }
 ]
}