{
 "title": "VoltDB Procedures",
 "tags": [
  "voltdb",
  "procedures"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({namespace=\"$cluster\",host_name=~\"$host\"},site_id)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},partition_id)"
    }
   },
   {
    "name": "procedure",
    "label": "Procedure",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},procedure_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Procedures Overview (Rate Errors Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Invocation rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\n(\n    rate\n    (\n        voltdb_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "stat",
   "description": "The number of times the procedure failed unexpectedly.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        voltdb_procedure_failed_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Abort rate",
   "type": "stat",
   "description": "The number of times the procedure was aborted.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        voltdb_procedure_aborted_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Worst case time",
   "type": "stat",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\"\n    }\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "Procedures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Procedures invocation counts ($procedure)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        voltdb_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "procedures / total"
    }
   ]
  },
  {
   "title": "Hottest procedures ($procedure)",
   "type": "table",
   "description": "The total number of invocations of this procedure at this site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure_name)\n(\n    increase(voltdb_procedure_invoked_total\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }[$__range])\n)",
     "legendFormat": "{{procedure_name}}"
    }
   ]
  },
  {
   "title": "Execution times distribution ($procedure)",
   "type": "heatmap",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(voltdb_procedure_invoked_time_seconds_bucket\n{\n    namespace=\"$cluster\",\n    host_name=~\"$host\",\n    partition_id=~\"$partition\",\n    procedure_name=~\"$procedure\"\n}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Top procedure invocation times ($procedure)",
   "type": "timeseries",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(\n    max by (procedure_name)\n    (\n        voltdb_procedure_invoked_time_seconds_max\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"\n        }\n    )\n)",
     "legendFormat": "{{procedure_name}}"
    }
   ]
  },
  {
   "title": "Slowest procedures ($procedure)",
   "type": "table",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure_name)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
     "legendFormat": "{{procedure_name}}"
    }
   ]
  },
  {
   "title": "Top procedure invocation counts ($procedure)",
   "type": "timeseries",
   "description": "The total number of invocations of this procedure at this site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sort(\n    max by (procedure_name)\n    (\n        rate(voltdb_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"\n        }[$__rate_interval])\n    )\n)",
     "legendFormat": "{{procedure_name}}"
    }
   ]
  },
  {
   "title": "Average result size ($procedure)",
   "type": "timeseries",
   "description": "The total size of the results returned by the procedure.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(voltdb_procedure_result_size_bytes{\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"}\n [$__rate_interval]))",
     "legendFormat": "Avg"
    }
   ]
  },
  { "title": "Execution time matrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Procedures x Hostame execution time matrix ($procedure) - size proportional to time",
   "type": "marcusolsson-treemap-panel",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure_name, host_name)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
     "legendFormat": "{{host_name}} / {{procedure_name}}"
    }
   ]
  },
  {
   "title": "Procedures x Hostame execution time matrix ($procedure)",
   "type": "table",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (procedure_name, host_name)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Procedures x Partition execution time matrix ($procedure)",
   "type": "table",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure_name, partition_id)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}