{
 "title": "VoltDB XDCR Active-Active",
 "tags": [
  "voltdb",
  "xdcr"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Clusters", "query": { "query": "label_values(cluster)" } },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({cluster=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({cluster=\"$cluster\", hostname=~\"$host\"},partitionid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status of replication to other clusters",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "voltdb_drproducer_replication_info{namespace=~\"$cluster\"}"
    }
   ]
  },
  { "title": "$cluster - Producer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "cluster" },
  {
   "title": "Size of pending tuples",
   "type": "gauge",
   "description": "The total number of bytes currently queued for transmission\nto the replica.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drproducer_total_queued_bytes{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Memory queues size",
   "type": "gauge",
   "description": "The total number of bytes of queued data currently held\nin memory. If the amount of total bytes is larger than the\namount in memory, the remainder is kept in overflow storage on disk.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drproducer_total_queued_in_memory_bytes{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Buffers usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((10 * 1024 * 1024) -voltdb_drproducer_consumer_available_bytes{cluster=\"$cluster\",hostname=~\"$host\"}) / (10 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Last acknowledged transaction",
   "type": "stat",
   "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(voltdb_drproducer_last_acked_timestamp_seconds{cluster=\"$cluster\",hostname=~\"$host\"}* 1000)"
    }
   ]
  },
  {
   "title": "Replication lag (5m max)",
   "type": "gauge",
   "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(replication_rtt_5m_max{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Queue gap",
   "type": "stat",
   "description": "The number of missing transactions between those already\nacknowledged by the consumer and the next available for\ntransmission. Under normal operating conditions, this value\nis zero.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drproducer_missing_txn_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "$cluster - Consumer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "cluster" },
  {
   "title": "Average replication speed",
   "type": "gauge",
   "description": "The average rate of replication over the past minute.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_drconsumer_1min_avg_replication_bytes_per_second{cluster=\"$cluster\",hostname=~\"$host\"})"
    },
    {}
   ]
  },
  {
   "title": "Buffers usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((10 * 1024 * 1024) -voltdb_drconsumer_available_bytes{cluster=\"$cluster\",hostname=~\"$host\"}) / (10 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Last received transaction",
   "type": "stat",
   "description": "The timestamp of the last transaction received from the producer.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drconsumer_last_received_timestamp_seconds{cluster=\"$cluster\",hostname=~\"$host\"}) * 1000",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Duplicated buffers",
   "type": "gauge",
   "description": "The number of repeated buffers received after the initial\npackets were dropped because the queue was full.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_drconsumer_duplicate_buffers{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Ignored buffers",
   "type": "gauge",
   "description": "The number of buffers received but dropped because the\nqueue was full.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconsumer_ignored_buffers{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Replication lag (old)",
   "type": "gauge",
   "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drproducer_last_acked_timestamp_seconds{cluster=\"$cluster\",hostname=~\"$host\"}-voltdb_drproducer_last_queued_timestamp_seconds{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "$cluster - Conflicts Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "cluster" },
  {
   "title": "Last conflict",
   "type": "stat",
   "description": "The timestamp of the last conflict.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drconflicts_last_conflict_timestamp_seconds{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "All conflicts count",
   "type": "stat",
   "description": "The total number of conflicts that have been recorded for this table in this partition.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_total_conflict_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Divergences due to conflicts",
   "type": "stat",
   "description": "The number of conflicts that may have resulted in divergence between the clusters, which is a subset of the total conflicts.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_divergence_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Constraint violations",
   "type": "stat",
   "description": "The number of constraint violation conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_constraint_violation_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Missing rows",
   "type": "stat",
   "description": "The number of missing row conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_missing_row_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Timestamp mismatches",
   "type": "stat",
   "description": "The number of timestamp mismatch conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_timestamp_mismatch_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "$cluster - Conflicts Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Conflicts by type (host = $host, partition = $partition)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(voltdb_drconflicts_constraint_violation_count{cluster=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
       "legendFormat": "constraint violations"
      },
      {
       "expr": "sum(voltdb_drconflicts_divergence_count{cluster=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
       "legendFormat": "divergences"
      },
      {
       "expr": "sum(voltdb_drconflicts_missing_row_count{cluster=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
       "legendFormat": "missing rows"
      },
      {
       "expr": "sum(voltdb_drconflicts_timestamp_mismatch_count{cluster=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
       "legendFormat": "mismatches"
      }
     ]
    },
    {
     "title": "Conflicts by host (host = $host, partition = $partition)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (hostname) ({__name__=~\"voltdb_drconflicts_constraint_violation_count|voltdb_drconflicts_missing_row_count|voltdb_drconflicts_timestamp_mismatch_count\", cluster=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Divergences by host (host = $host, partition = $partition)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 10, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (hostname) (voltdb_drconflicts_divergence_count{cluster=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Conflicts by table (host = $host, partition = $partition)",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 13, "w": 14, "x": 10, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (__name__, tablename) ({__name__=~\"voltdb_drconflicts_constraint_violation_count|voltdb_drconflicts_divergence_count|voltdb_drconflicts_missing_row_count|voltdb_drconflicts_timestamp_mismatch_count\", cluster=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster - Consumer details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of replication (1m moving average)",
     "type": "timeseries",
     "description": "Exponentially weighted moving average rate of replication over the past minute.\ndata rate is measured in bytes per second",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "repeat": "cluster",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (hostname) (voltdb_drconsumer_1min_avg_replication_bytes_per_second{cluster=\"$cluster\",hostname=~\"$host\"})",
       "legendFormat": "{{partitionid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster - Producer details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers sent but not yet acknowledged (per partition)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (partitionid) (voltdb_drproducer_total_buffer_count{cluster=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"})",
       "legendFormat": "{{partitionid}}"
      }
     ]
    },
    {
     "title": "The timestamp of the last transaction queued for transmission to the consumer. (per host, per partition)",
     "type": "marcusolsson-treemap-panel",
     "description": "The timestamp of the last transaction queued for transmission to the consumer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "max by (hostname, partitionid) (voltdb_drproducer_last_queued_timestamp_seconds{cluster=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"} * 1000)"
      },
      { "expr": "1" }
     ]
    },
    {
     "title": "Timestamp of the last transaction queued for transmission to the consumer. (per partition)",
     "type": "timeseries",
     "description": "The timestamp of the last transaction queued for transmission to the consumer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "max by (partitionid) (voltdb_drproducer_last_queued_timestamp_seconds{cluster=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"} * 1000 > 1199145600000)",
       "legendFormat": "{{partitionid}}"
      }
     ]
    }
   ]
  }
 ]
}