{
 "title": "Volt Partitions",
 "tags": [
  "voltdb",
  "partitions",
  "voltactivedata"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\"},partitionid)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\"},siteid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions overview (Rate Errors Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocation rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\"}[$__interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Command execution max wait time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_queue_max_wait_seconds{job=~\"$job\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max queue depth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_queue_depth{job=~\"$job\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Max wait across sites",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_queue_max_wait_seconds{job=~\"$job\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Percent busy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - max(voltdb_idletime_idle_ratio{job=~\"$job\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TPS ($partition)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partitionid)(rate(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"}[$__interval]))",
     "legendFormat": "{{partitionid}}"
    },
    {
     "expr": "sum (rate(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Busiest sites (percent of the time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (siteid)(100-voltdb_idletime_idle_ratio{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\"})",
     "legendFormat": "{{siteid}}"
    }
   ]
  },
  {
   "title": "Procedure invocations per partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(partitionid)(rate(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"}[$__interval]))",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Procedure failures per partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(partitionid)(rate(voltdb_procedure_failures{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"}[$__interval]))",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Procedure failures per partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(partitionid)(rate(voltdb_procedure_failures{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"}[$__interval]))",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Top executed procedures",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(procedure)(increase(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"}[$__interval]))",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Procedures x Partition execution time matrix",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (procedure, partitionid)(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"})"
    },
    {
     "expr": "sum by (procedure, partitionid)(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"})"
    }
   ]
  },
  {
   "title": "Command queue depth by site",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_queue_depth{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\"}",
     "legendFormat": "{{siteid}}"
    }
   ]
  },
  {
   "title": "Command queue max wait times by site",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(voltdb_queue_max_wait_seconds{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\"})",
     "legendFormat": "{{siteid}}"
    }
   ]
  },
  {
   "title": "Tuples in table by table and partition",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tablename, partitionid)(voltdb_table_tuple_count{job=~\"$job\",hostname=~\"$host\",siteid=~\"$site\",partitionid=~\"$partition\"})"
    },
    { "expr": "1" }
   ]
  }
 ]
}