{
 "title": "VoltDB Cluster overview",
 "tags": [
  "voltdb",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_latency_tps{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Procedure errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_procedure_aborts{namespace=\"$cluster\",hostname=~\"$host\"})+max(voltdb_procedure_failures{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (voltdb_latency_99th_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Commandlog queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_commandlog_outstanding_txns{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 } },
  {
   "title": "Max CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (voltdb_cpu_usage_percent{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "VoltDB RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_memory_rss_bytes{namespace=\"$cluster\",hostname=~\"$host\"}/ on (hostname) voltdb_memory_physicalmemory_bytes{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Java Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_memory_javaused_bytes{namespace=\"$cluster\",hostname=~\"$host\"}/ on (hostname) voltdb_memory_javamaxheap_bytes{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_gc_newgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}) + sum( voltdb_gc_oldgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "Sum dropped connections"
    }
   ]
  },
  { "title": "Cluster Advisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum by (hostname) (voltdb_gc_newgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"})+ sum by (hostname) (voltdb_gc_oldgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "Rebalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_moved_ratio{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "In progress"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Transaction rate per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(hostname)(voltdb_latency_tps{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Max procedure execution time (just the procedure)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (procedure)(voltdb_procedure_max_execution_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "Max request execution time (whole VoltDB path)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(hostname)(voltdb_latency_max_seconds{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Connections and limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Unfinished Transactions VoltDB knows about",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_liveclients_outstanding_txns{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Finished Transactions VoltDB is about to send back to the client",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_liveclients_outstanding_reponse_messages{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Client transaction rate by connected host",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cnxhostname, hostname)(increase(voltdb_iostats_received_messages{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval]))",
     "legendFormat": "{{cnxhostname}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "New Gen GC Time (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "voltdb_gc_newgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "New Gen GC Count (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voltdb_gc_newgen_gc_count{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Old Gen GC Time (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(voltdb_gc_oldgen_avg_gc_time_seconds{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Old Gen GC Count (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(voltdb_gc_oldgen_gc_count{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Java Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "voltdb_memory_javaused_bytes{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "voltdb_memory_rss_bytes{namespace=\"$cluster\",hostname=~\"$host\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rebalance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Calls per second",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(voltdb_rebalance_calls_per_seconds{namespace=\"$cluster\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Estimated remaining time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_remaining_time_seconds{namespace=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Rebalance progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "voltdb_rebalance_moved_ratio{namespace=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average data transfer time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_avg_data_transfer_time_seconds{namespace=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average execution time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_rebalance_avg_execution_time_seconds{namespace=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}