{
 "title": "Volt Export",
 "tags": [
  "voltdb",
  "export",
  "voltactivedata"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\"},partitionid)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\"},source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending tuples",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_export_pending_tuples_count{job=~\"$job\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Total queued tuples",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(voltdb_export_total_queued_tuples_count{job=~\"$job\",hostname=~\"$host\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total missing tuples",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_missing_tuples_count{job=~\"$job\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max export latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_export_max_latency_seconds{job=~\"$job\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Acknowledgements lag (max across partitions)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (partitionid) (voltdb_export_max_latency_seconds)",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Acknowledgements lag (max across sources)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (source) (voltdb_export_max_latency_seconds)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Average Export latency per partition",
   "type": "timeseries",
   "description": "Average export latency per partition ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (partitionid, source) (voltdb_export_avg_latency_seconds{job=~\"$job\",hostname=~\"$host\"})",
     "legendFormat": "{{source}} : {{partitionid}}"
    }
   ]
  },
  {
   "title": "Avg Export latency per node",
   "type": "timeseries",
   "description": "Average export latency per node",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (hostname, source) (voltdb_export_avg_latency_seconds{job=~\"$job\",hostname=~\"$host\"})",
     "legendFormat": "AVG {{hostname}}"
    }
   ]
  },
  {
   "title": "Pending tuples count by source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (voltdb_export_pending_tuples_count)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Missing tuples count by source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (voltdb_export_missing_tuples_count)",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}