{
 "title": "Volt Import",
 "tags": [
  "import",
  "voltdb",
  "voltactivedata"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\"},partitionid)"
    }
   },
   {
    "name": "Procedure",
    "label": "Procedure",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\",partitionid=~\"$partition\"}, procedure)"
    }
   },
   {
    "name": "siteID",
    "label": "siteID",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\"},siteid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(voltdb_import_successful_txns {hostname=~\"$host\", job=~\"$job\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(increase(voltdb_import_failed_txns {hostname=~\"$host\", job=~\"$job\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Import Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Successful import Transactions by host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (hostname, procname) (voltdb_import_successful_txns {hostname=~\"$host\", procname=~\"$Procedure\"})",
     "legendFormat": "{{hostname}} : {{procname}}"
    }
   ]
  },
  {
   "title": "Failed import Transactions by host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (hostname, procname) (voltdb_import_failed_txns {hostname=~\"$host\", procname=~\"$Procedure\"})",
     "legendFormat": "{{hostname}} : {{procname}}"
    }
   ]
  },
  {
   "title": "import retries by host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (hostname, procname) (voltdb_import_retries{hostname=~\"$host\", job=~\"$job\", procname=~\"$Procedure\"})",
     "legendFormat": "{{hostname}} : {{procname}}"
    }
   ]
  },
  {
   "title": "Outstanding Tuples by host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by (hostname) (voltdb_import_outstanding_tuples {hostname=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}