{
 "title": "VoltDB Operator",
 "description": "voltdb-operator prometheus",
 "tags": [
  "voltdb",
  "voltdb-operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,2h,4h,8h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "query": "label_values(voltdbcluster_info, voltdbcluster)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 1, "y": 1 },
   "content": "![voltimage](https://avatars3.githubusercontent.com/u/703910?s=200&v=4)"
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (server) (voltdbcluster_info{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(voltdb_memory_nodecount{namespace=~\"$namespace\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Reconciliation Activity",
   "type": "graph",
   "description": "Total number of reconciliations",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}[$interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "description": "Length of time per reconciliation per controller",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_time_seconds_bucket{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "graph",
   "description": "Number of HTTP requests, partitioned by status code, method, and host.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rest_client_requests_total{job=\"voltdb-operator-metrics\", namespace=~\"$namespace\"}[$interval])) by (code, host, method)",
     "legendFormat": "{{code}} {{host}} {{method}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "graph",
   "description": "Current depth of workqueue",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\",name=~\"voltdb.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Queue Duration",
   "type": "heatmap",
   "description": "How long in seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(workqueue_queue_duration_seconds_bucket{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Controller Workflow Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(workqueue_retries_total{job=\"voltdb-operator-metrics\", namespace=~\"$namespace\"}[$interval])) by (name)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Work Duration",
   "type": "heatmap",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(workqueue_work_duration_seconds_bucket{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Controller Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"voltdb-operator-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}