{
 "title": "VoltDB Tables",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({cluster=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values({cluster=\"$cluster\", hostname=~\"$host\"},tablename)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({cluster=\"$cluster\", hostname=~\"$host\",tablename=~\"$table\"}, partitionid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Procedures Overview (Rate Errors Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Table allocated memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_table_tuple_allocated_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Tuple count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_table_tuple_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Index memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_index_memory_estimate_bytes{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Number of index entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_index_entries_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Table sizes ($table)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(tablename)(voltdb_table_tuple_allocated_memory_bytes{cluster=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\",tablename=~\"$table\"})",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Tuple count by partition matrix (table == $table, partition == $partition)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tablename, partitionid)(voltdb_table_tuple_count{cluster=\"$cluster\",hostname=~\"$host\",tablename=~\"$table\",partitionid=~\"$partition\"})"
    },
    { "expr": "1" }
   ]
  },
  {
   "title": "Hosts by partitions",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname, partitionid)(voltdb_table_tuple_count{cluster=\"$cluster\",hostname=~\"$host\"})"
    },
    { "expr": "1" }
   ]
  },
  {
   "title": "Index name by partition matrix (table == $table, partition == $partition)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (indexname, partitionid)(voltdb_index_entries_count{cluster=\"$cluster\",hostname=~\"$host\",tablename=~\"$table\",partitionid=~\"$partition\"})"
    },
    {
     "expr": "sum by (indexname, partitionid)(voltdb_index_memory_estimate_bytes{cluster=\"$cluster\",hostname=~\"$host\",tablename=~\"$table\",partitionid=~\"$partition\"})"
    }
   ]
  }
 ]
}