{
 "title": "VoltDB XDCR Active-Passive",
 "tags": [
  "voltdb",
  "xdcr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "active", "label": "Active", "query": { "query": "label_values(namespace)" } },
   { "name": "passive", "label": "Passive", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\",partitionid=~\"$partition\"}, source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status of replication to other clusters",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "voltdb_drproducer_replication_info{namespace=~\"$active|$passive\"}"
    }
   ]
  },
  {
   "title": "Producer Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of pending tuples",
     "type": "gauge",
     "description": "The total number of bytes currently queued for transmission\nto the replica.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(voltdb_drproducer_total_queued_bytes{namespace=\"$active\",hostname=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Memory queues size",
     "type": "gauge",
     "description": "The total number of bytes of queued data currently held\nin memory. If the amount of total bytes is larger than the\namount in memory, the remainder is kept in overflow storage on disk.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(voltdb_drproducer_total_queued_in_memory_bytes{namespace=\"$active\",hostname=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Buffers usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(((10 * 1024 * 1024) -voltdb_drproducer_consumer_available_bytes{namespace=\"$active\",hostname=~\"$host\"}) / (10 * 1024 * 1024))"
      }
     ]
    },
    {
     "title": "Last acknowledged transaction",
     "type": "stat",
     "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(voltdb_drproducer_last_acked_timestamp_seconds{namespace=\"$active\",hostname=~\"$host\"}* 1000)"
      }
     ]
    },
    {
     "title": "Replication lag (5m max)",
     "type": "gauge",
     "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(replication_rtt_5m_max{namespace=\"$active\",hostname=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Queue gap",
     "type": "stat",
     "description": "The number of missing transactions between those already\nacknowledged by the consumer and the next available for\ntransmission. Under normal operating conditions, this value\nis zero.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(voltdb_drproducer_missing_txn_count{namespace=\"$active\",hostname=~\"$host\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average replication speed",
     "type": "gauge",
     "description": "The average rate of replication over the past minute.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(voltdb_drconsumer_1min_avg_replication_bytes_per_second{namespace=\"$passive\",hostname=~\"$host\"})"
      },
      {}
     ]
    },
    {
     "title": "Buffers usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(((10 * 1024 * 1024) -voltdb_drconsumer_available_bytes{namespace=\"$passive\",hostname=~\"$host\"}) / (10 * 1024 * 1024))"
      }
     ]
    },
    {
     "title": "Last received transaction",
     "type": "stat",
     "description": "The timestamp of the last transaction received from the producer.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(voltdb_drconsumer_last_received_timestamp_seconds{namespace=\"$passive\",hostname=~\"$host\"}) * 1000",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Duplicated buffers",
     "type": "gauge",
     "description": "The number of repeated buffers received after the initial\npackets were dropped because the queue was full.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(voltdb_drconsumer_duplicate_buffers{namespace=\"$passive\",hostname=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Ignored buffers",
     "type": "gauge",
     "description": "The number of buffers received but dropped because the\nqueue was full.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(voltdb_drconsumer_ignored_buffers{namespace=\"$passive\",hostname=~\"$host\"})"
      }
     ]
    }
   ]
  },
  { "title": "Conflicts overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Last conflict",
   "type": "stat",
   "description": "The timestamp of the last conflict.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drconflicts_last_conflict_timestamp_seconds{namespace=~\"$active|$passive\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Rate of replication (1m moving average)",
   "type": "timeseries",
   "description": "Exponentially weighted moving average rate of replication over the past minute.\ndata rate is measured in bytes per second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (hostname) (voltdb_drconsumer_1min_avg_replication_bytes_per_second{namespace=\"$passive\",hostname=~\"$host\"})",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Timestamp of the last transaction queued for transmission to the consumer. (per partition)",
   "type": "timeseries",
   "description": "The timestamp of the last transaction queued for transmission to the consumer.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "max by (partitionid) (voltdb_drproducer_last_queued_timestamp_seconds{namespace=\"$active\",hostname=~\"$host\"} * 1000 > 1199145600000)",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Buffers sent but not yet acknowledged (per partition)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partitionid) (voltdb_drproducer_total_buffer_count{namespace=\"$active\",hostname=~\"$host\"})",
     "legendFormat": "{{partitionid}}"
    }
   ]
  }
 ]
}