{
 "title": "VoltDB Partitions",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},table_name)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\", table_name=~\"$table\"},partition_id)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},site_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions overview (Rate Errors Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Invocation rate 5m",
   "type": "stat",
   "description": "The number of procedure invocation per 5 minutes, also includes procedures being replicated into partition replicas, so it does not equal the number of transactions issued by clients",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_procedure_invoked_total{namespace=\"$cluster\",host_name=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Command execution max wait time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_task_queue_wait_time_seconds_max{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max queue depth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_task_queue_depth_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Max percent busy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(1 - (voltdb_idle_time_pauses_seconds_sum{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"})/60)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Procedure invocations per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(partition_id)(rate(voltdb_procedure_invoked_total{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\",partition_id=~\"$partition\"}[$__rate_interval]))",
     "legendFormat": "{{partition_id}}"
    }
   ]
  },
  {
   "title": "Busiest sites (percent of the time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (site_id) (1- voltdb_idle_time_pauses_seconds_sum{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\"}/60)",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Top executed procedures",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(procedure_name)(increase(voltdb_procedure_invoked_total{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\",partition_id=~\"$partition\"}[$__range]))",
     "legendFormat": "{{partition_id}}"
    }
   ]
  },
  {
   "title": "Procedure failures per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(partition_id)(rate(voltdb_procedure_failed_total{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\",partition_id=~\"$partition\"}[$__rate_interval]))",
     "legendFormat": "{{partition_id}}"
    }
   ]
  },
  {
   "title": "Procedure invocations count by time buckets",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(voltdb_procedure_invoked_time_seconds_bucket{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\",partition_id=~\"$partition\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Procedures x Partition execution time matrix",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(procedure_name, partition_id) (voltdb_procedure_invoked_time_seconds_max{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\",partition_id=~\"$partition\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(procedure_name, partition_id) (increase(voltdb_procedure_invoked_total{namespace=\"$cluster\", host_name=~\"$host\", site_id=~\"$site\", partition_id=~\"$partition\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command queue depth by site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_task_queue_depth_total{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\"}",
     "legendFormat": "{{site_id}}"
    }
   ]
  },
  {
   "title": "Cumulative Procedure Invocation Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(voltdb_procedure_invoked_time_seconds_bucket{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\",partition_id=~\"$partition\"}[$__rate_interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Tuples in table by table and partition",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (table_name, partition_id)(voltdb_table_tuple_total{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\",partition_id=~\"$partition\"})",
     "legendFormat": "__auto"
    },
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Command queue max wait times by site",
   "type": "timeseries",
   "description": "Cumulative queue wait time. Choose site to drill down",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(voltdb_task_queue_wait_time_seconds_bucket{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(voltdb_task_queue_wait_time_seconds_bucket{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(voltdb_task_queue_wait_time_seconds_bucket{namespace=\"$cluster\",host_name=~\"$host\",site_id=~\"$site\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    }
   ]
  }
 ]
}