{
 "title": "VoltDB Import",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "importer",
    "label": "Importer",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\"}, importername)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\"},siteid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (importer = $importer)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current successful transaction rate",
   "type": "gauge",
   "description": "The number of import transactions that succeeded.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_import_successful_txns{namespace=\"$cluster\",importername=~\"$importer\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Currently outstanding tuples",
   "type": "gauge",
   "description": "The number of records read from the import stream and waiting to be inserted into the database.\n\nCan be negative due to race condition between procedure finishing and DB insert being reported.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_import_outstanding_tuples{namespace=\"$cluster\",importername=~\"$importer\"})"
    }
   ]
  },
  {
   "title": "Currently failing transactions",
   "type": "gauge",
   "description": "The number of import transactions that failed.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_import_failed_txns{namespace=\"$cluster\",importername=~\"$importer\"})"
    }
   ]
  },
  {
   "title": "Current retries",
   "type": "gauge",
   "description": "The number of attempts to replay failed transactions.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_import_retries{namespace=\"$cluster\",importername=~\"$importer\"})"
    }
   ]
  },
  { "title": "Details (importer = $importer)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "All transactions by procedure name",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (procname) (voltdb_import_successful_txns{namespace=\"$cluster\",hostname=~\"$host\",importername=~\"$importer\"})",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "All failed transactions by procedure name",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (procname) (voltdb_import_failed_txns{namespace=\"$cluster\",hostname=~\"$host\",importername=~\"$importer\"})",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "Successful transactions by host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(voltdb_import_successful_txns{namespace=\"$cluster\",hostname=~\"$host\",importername=~\"$importer\"}[$__interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Failed transactions by host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (voltdb_import_failed_txns{namespace=\"$cluster\",hostname=~\"$host\",importername=~\"$importer\"})",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Successful transactions by procedure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (procname) (rate(voltdb_import_successful_txns{namespace=\"$cluster\",hostname=~\"$host\",importername=~\"$importer\"}[$__interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Failed transactions by procedure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (procname) (voltdb_import_failed_txns{namespace=\"$cluster\",hostname=~\"$host\",importername=~\"$importer\"})",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}