{
 "title": "VoltDB XDCR",
 "tags": [
  "voltdb",
  "xdcr"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\"},partitionid)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\",partitionid=~\"$partition\"}, source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Producer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XDCR readiness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_xdcr_readiness_info{namespace=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Replication lag (5m max)",
   "type": "gauge",
   "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drproducer_replication_roundtriptime_5m_max_seconds{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Buffers usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((10 * 1024 * 1024) -voltdb_drproducer_consumer_available_bytes{namespace=\"$cluster\",hostname=~\"$host\"}) / (10 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Size of pending tuples",
   "type": "gauge",
   "description": "The total number of bytes currently queued for transmission\nto the replica.",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drproducer_total_queued_bytes{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Memory queues size",
   "type": "gauge",
   "description": "The total number of bytes of queued data currently held\nin memory. If the amount of total bytes is larger than the\namount in memory, the remainder is kept in overflow storage on disk.",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drproducer_total_queued_in_memory_bytes{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Queue gap",
   "type": "stat",
   "description": "The number of missing transactions between those already\nacknowledged by the consumer and the next available for\ntransmission. Under normal operating conditions, this value\nis zero.",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drproducer_missing_txn_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Last acknowledged transaction",
   "type": "stat",
   "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(voltdb_drproducer_last_acked_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\"}* 1000)"
    }
   ]
  },
  { "title": "Consumer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Average replication speed",
   "type": "gauge",
   "description": "The average rate of replication over the past minute.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_drconsumer_1min_avg_replication_bytes_per_second{namespace=\"$cluster\",hostname=~\"$host\"})"
    },
    {}
   ]
  },
  {
   "title": "Buffers usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((10 * 1024 * 1024) -voltdb_drconsumer_available_bytes{namespace=\"$cluster\",hostname=~\"$host\"}) / (10 * 1024 * 1024))"
    }
   ]
  },
  {
   "title": "Last received transaction",
   "type": "stat",
   "description": "The timestamp of the last transaction received from the producer.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drconsumer_last_received_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\"}) * 1000",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Duplicated buffers",
   "type": "gauge",
   "description": "The number of repeated buffers received after the initial\npackets were dropped because the queue was full.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_drconsumer_duplicate_buffers{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Ignored buffers",
   "type": "gauge",
   "description": "The number of buffers received but dropped because the\nqueue was full.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconsumer_ignored_buffers{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Conflicts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Last conflict",
   "type": "stat",
   "description": "The timestamp of the last conflict.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drconflicts_last_conflict_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\"})"
    },
    {}
   ]
  },
  {
   "title": "All conflicts count",
   "type": "stat",
   "description": "The total number of conflicts that have been recorded for this table in this partition.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_total_conflict_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Divergences due to conflicts",
   "type": "stat",
   "description": "The number of conflicts that may have resulted in divergence between the clusters, which is a subset of the total conflicts.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_divergence_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Constraint violations",
   "type": "stat",
   "description": "The number of constraint violation conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_constraint_violation_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Missing rows",
   "type": "stat",
   "description": "The number of missing row conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_missing_row_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Timestamp mismatches",
   "type": "stat",
   "description": "The number of timestamp mismatch conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_timestamp_mismatch_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Conflicts by type (host = $host, partition = $partition)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(voltdb_drconflicts_constraint_violation_count{namespace=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
     "legendFormat": "constraint violations"
    },
    {
     "expr": "sum(voltdb_drconflicts_divergence_count{namespace=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
     "legendFormat": "divergences"
    },
    {
     "expr": "sum(voltdb_drconflicts_missing_row_count{namespace=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
     "legendFormat": "missing rows"
    },
    {
     "expr": "sum(voltdb_drconflicts_timestamp_mismatch_count{namespace=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
     "legendFormat": "mismatches"
    }
   ]
  },
  {
   "title": "Conflicts by host (host = $host, partition = $partition)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) ({__name__=~\"voltdb_drconflicts_constraint_violation_count|voltdb_drconflicts_missing_row_count|voltdb_drconflicts_timestamp_mismatch_count\", namespace=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Divergences by host (host = $host, partition = $partition)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (voltdb_drconflicts_divergence_count{namespace=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Conflicts by table (host = $host, partition = $partition)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (__name__, tablename) ({__name__=~\"voltdb_drconflicts_constraint_violation_count|voltdb_drconflicts_divergence_count|voltdb_drconflicts_missing_row_count|voltdb_drconflicts_timestamp_mismatch_count\", namespace=\"$cluster\",hostname=~\"$host\", partitionid=~\"$partition\"})"
    }
   ]
  },
  { "title": "Producer details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Buffers sent but not yet acknowledged (per partition)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partitionid) (voltdb_drproducer_total_buffer_count{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"})",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Buffers sent but not yet acknowledged (per host, per partition)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname, partitionid) (voltdb_drproducer_total_buffer_count{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"})"
    },
    { "expr": "1" }
   ]
  },
  {
   "title": "Bytes queued for transmission to the replica (per partition)",
   "type": "timeseries",
   "description": "The total number of bytes currently queued for transmission\nto the replica",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (partitionid) (voltdb_drproducer_total_queued_bytes{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"})",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Bytes queued for transmission to the replica (per host, per partition)",
   "type": "marcusolsson-treemap-panel",
   "description": "The total number of bytes currently queued for transmission\nto the replica",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname, partitionid) (voltdb_drproducer_total_buffer_count{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"})"
    },
    { "expr": "1" }
   ]
  },
  {
   "title": "Timestamp of the last transaction queued for transmission to the consumer. (per partition)",
   "type": "timeseries",
   "description": "The timestamp of the last transaction queued for transmission to the consumer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "max by (partitionid) (voltdb_drproducer_last_queued_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"} * 1000 > 1199145600000)",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "The timestamp of the last transaction queued for transmission to the consumer. (per host, per partition)",
   "type": "marcusolsson-treemap-panel",
   "description": "The timestamp of the last transaction queued for transmission to the consumer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "max by (hostname, partitionid) (voltdb_drproducer_last_queued_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"} * 1000)"
    },
    { "expr": "1" }
   ]
  },
  { "title": "Consumer details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Rate of replication (1m moving average)",
   "type": "timeseries",
   "description": "Exponentially weighted moving average rate of replication over the past minute.\ndata rate is measured in bytes per second",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (hostname) (voltdb_drconsumer_1min_avg_replication_bytes_per_second{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Duplicated buffers (by host)",
   "type": "timeseries",
   "description": "Exponentially weighted moving average rate of replication over the past minute.\ndata rate is measured in bytes per second",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (voltdb_drconsumer_duplicate_buffers{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Duplicated buffers (by partition, host)",
   "type": "timeseries",
   "description": "Exponentially weighted moving average rate of replication over the past minute.\ndata rate is measured in bytes per second",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partitionid, hostname) (voltdb_drconsumer_duplicate_buffers{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}-{{partitionid}}"
    }
   ]
  },
  {
   "title": "Last received timestamp (min, by host)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "min by (hostname) (voltdb_drconsumer_last_received_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"} * 1000)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Last received timestamp (by hostname)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "min by (partitionid, hostname) (voltdb_drconsumer_last_received_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"} * 1000)",
     "legendFormat": "{{hostname}}-{{partitionid}}"
    }
   ]
  },
  {
   "title": "Available buffers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname, partitionid) (voltdb_drconsumer_available_buffers{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\"})",
     "legendFormat": "{{hostname}} ({{partitionid}})"
    }
   ]
  }
 ]
}