{
 "title": "VoltDB TTL",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "tableName",
    "label": "Table name",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},table_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last execution time",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "voltdb_ttl_last_execution_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\", table_name=~\"$tableName\"} * 1000",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "All Rows Deleted",
   "type": "stat",
   "description": "Rows deleted for all TTL tables",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(increase(voltdb_ttl_rows_deleted_total{namespace=~\"$cluster\", host_name=~\"$host\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (table_name) (voltdb_ttl_failed_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining rows",
   "type": "stat",
   "description": "Rows remaining for all TTL tables",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum (voltdb_ttl_rows_remaining_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows deleted by table name",
   "type": "timeseries",
   "description": "Number of deletes per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(voltdb_ttl_rows_deleted_total{namespace=\"$cluster\",host_name=~\"$host\", table_name=~\"$tableName\"}[$__rate_interval])",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Failures by table name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(voltdb_ttl_failed_total{namespace=\"$cluster\",host_name=~\"$host\", table_name=~\"$tableName\"}[$__rate_interval])",
     "legendFormat": "{{table_name}}"
    }
   ]
  }
 ]
}