{
 "title": "VoltDB Export",
 "tags": [
  "voltdb",
  "export"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},partition_id)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\",partition_id=~\"$partition\"},table_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total tuples sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(voltdb_export_tuple_count_total{namespace=\"$cluster\",host_name=~\"$host\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total missing tuples",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_queue_gap_total{namespace=\"$cluster\",host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Pending tuples",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_tuple_pending_total{namespace=\"$cluster\",host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max export latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_export_latency_seconds_max{namespace=\"$cluster\",host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Active export streams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_info{namespace=\"$cluster\",host_name=~\"$host\",export_is_active=\"TRUE\"})"
    }
   ]
  },
  {
   "title": "Inactive export streams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_info{namespace=\"$cluster\",host_name=~\"$host\",export_is_active=\"FALSE\"})"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending tuples count by source and partition",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "voltdb_export_tuple_pending_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing tuples count by source and partition",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partition_id, export_target)(voltdb_export_queue_gap_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"})"
    }
   ]
  },
  {
   "title": "Acknowledgements lag (max across partitions)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (partition_id) (time()* 1000-voltdb_export_last_acked_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"})/1000",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Acknowledgements lag (max across servers and partitions)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (table_name) (time()* 1000-voltdb_export_last_acked_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"})/1000",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Pending tuples by source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (table_name) (voltdb_export_tuple_pending_total)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Missing tuples by source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (table_name) (voltdb_export_queue_gap_total)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Export activity timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Export timeline",
   "type": "state-timeline",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "group by (host_name, table_name, export_is_active, partition_id) (voltdb_export_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\", export_is_active=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}