{
 "title": "VoltDB Tasks",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   { "name": "host", "label": "Host", "query": { "query": "label_values(host_name)" } },
   { "name": "partition", "label": "Partition", "query": { "query": "label_values(partition_id)" } },
   { "name": "taskName", "label": "Task Name", "query": { "query": "label_values(task_name)" } },
   { "name": "taskOrigin", "label": "Task Origin", "query": { "query": "label_values(task_origin)" } },
   { "name": "taskScope", "label": "Task Scope", "query": { "query": "label_values(task_scope)" } },
   { "name": "taskStatus", "label": "Task Status", "query": { "query": "label_values(task_status)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled tasks",
   "type": "stat",
   "description": "All non-cancelled scheduled tasks in cluster",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_name, host_name) (voltdb_scheduler_action_status_info{namespace=\"$cluster\",host_name=~\"$host\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\",task_status!=\"CANCELED\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique tasks",
   "type": "stat",
   "description": "Unique tasks scheduled in cluster by name",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_name) (voltdb_scheduler_action_status_info{namespace=\"$cluster\",host_name=~\"$host\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Running",
   "type": "stat",
   "description": "Informational metric with scheduler metadata. Tags: PARTITION_ID - The numeric ID for the logical partition running the task procedure. Directed procedures run on each logical partition. Multi-partition procedures run on the multi-partition initiator. TASK_NAME - The name of the task. TASK_STATUS - The current status of the task. Possible values include: RUNNING - The task is enabled and running normally; DISABLED - The task is disabled and not running. ERROR - The task returned an error and was stopped due to the ON ERROR STOP attribute. PAUSED - The database is paused or is running on a DR replica, so the task is not currently running but will restart when the database resumes or is promoted. TASK_ORIGIN - \"System\" or \"User\". TASK_SCOPE - The execution scope of the task, which matches the RUN ON attribute. Possible values are \"Database\", \"Hosts\", or \"Partitions\".",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_name) (voltdb_scheduler_action_status_info{namespace=\"$cluster\",host_name=~\"$host\", task_status!=\"RUNNING\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing tasks",
   "type": "stat",
   "description": "The number of times the procedure generated an error when run.Tags: same as above.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task_name) (voltdb_scheduler_procedure_failure_total{namespace=\"$cluster\",host_name=~\"$host\", task_name=~\"$taskName\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Action Status",
   "type": "table",
   "description": "Informational metric with scheduler metadata. Tags: PARTITION_ID - The numeric ID for the logical partition running the task procedure. Directed procedures run on each logical partition. Multi-partition procedures run on the multi-partition initiator. TASK_NAME - The name of the task. TASK_STATUS - The current status of the task. Possible values include: RUNNING - The task is enabled and running normally; DISABLED - The task is disabled and not running. ERROR - The task returned an error and was stopped due to the ON ERROR STOP attribute. PAUSED - The database is paused or is running on a DR replica, so the task is not currently running but will restart when the database resumes or is promoted. TASK_ORIGIN - \"System\" or \"User\". TASK_SCOPE - The execution scope of the task, which matches the RUN ON attribute. Possible values are \"Database\", \"Hosts\", or \"Partitions\".",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "voltdb_scheduler_action_status_info{namespace=\"$cluster\",host_name=~\"$host\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduled procedure invocation total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(voltdb_scheduler_task_invocation_total{\n            namespace=\"$cluster\",\n            host_name=~\"$host\", \n            task_name=~\"$taskName\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"\n        }[$__rate_interval])",
       "legendFormat": "{{host_name}}, partition({{partition_id}}): {{task_name}}"
      }
     ]
    },
    {
     "title": "Scheduled task execution time",
     "type": "heatmap",
     "description": "The distribution of the amount of time taken to schedule an instance of the task.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(voltdb_scheduler_task_execution_time_seconds_bucket\n{\n    namespace=\"$cluster\",\n    host_name=~\"$host\", task_name=~\"$taskName\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"\n}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Scheduled task wait time",
     "type": "heatmap",
     "description": "The distribution of the difference between when the task was scheduled to run and when the scheduler was invoked.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(voltdb_scheduler_task_wait_time_seconds_bucket\n{\n    namespace=\"$cluster\",\n    host_name=~\"$host\", task_name=~\"$taskName\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"\n}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Procedures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduled procedure invocation total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "rate(voltdb_scheduler_procedure_invocation_total{\n            namespace=\"$cluster\",\n            host_name=~\"$host\", task_name=~\"$taskName\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"\n        }[$__rate_interval])",
       "legendFormat": "{{host_name}}, partition({{partition_id}}): {{task_name}}"
      }
     ]
    },
    {
     "title": "Scheduled procedure invocation failing",
     "type": "timeseries",
     "description": "The number of times the procedure generated an error when run.Tags: same as above.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "rate(voltdb_scheduler_procedure_failure_total{\n            namespace=\"$cluster\",\n            host_name=~\"$host\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"\n        }[$__rate_interval])",
       "legendFormat": "{{host_name}}, partition({{partition_id}}): {{task_name}}"
      }
     ]
    },
    {
     "title": "Scheduled procedure execution time",
     "type": "heatmap",
     "description": "The distribution of time the task took to execute.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(rate(voltdb_scheduler_procedure_execution_time_seconds_bucket\n{\n    namespace=\"$cluster\",\n    host_name=~\"$host\", task_name=~\"$taskName\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"\n}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Scheduled procedure wait time",
     "type": "heatmap",
     "description": "The distribution of time between when the procedure was scheduled to run and when it was invoked.",
     "gridPos": { "h": 11, "w": 11, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum(rate(voltdb_scheduler_procedure_wait_time_seconds_bucket\n{\n    namespace=\"$cluster\",\n    host_name=~\"$host\", task_name=~\"$taskName\", task_scope=~\"$taskScope\", task_origin=~\"$taskOrigin\"\n}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}