{
 "title": "VoltDB Import",
 "time": { "from": "2024-06-05T13:09:06.253Z", "to": "2024-06-05T13:56:07.477Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "importer",
    "label": "Importer",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\"},importer_name)"
    }
   },
   {
    "name": "procedure",
    "label": "Procedures",
    "query": {
     "query": "label_values(voltdb_importer_success_total{namespace=\"$cluster\", hostname=~\"$host\"},procedure_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (importer = $importer)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current successful transaction rate",
   "type": "gauge",
   "description": "The number of import transactions that succeeded.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_importer_success_total{namespace=\"$cluster\",importer_name=~\"$importer\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Currently outstanding tuples",
   "type": "gauge",
   "description": "The number of records read from the import stream and waiting to be inserted into the database.\n\nCan be negative due to race condition between procedure finishing and DB insert being reported.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_importer_outstanding_requests_total{namespace=\"$cluster\",importer_name=~\"$importer\"})"
    }
   ]
  },
  {
   "title": "Currently failing transactions",
   "type": "gauge",
   "description": "The number of import transactions that failed.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_importer_failure_total{namespace=\"$cluster\",importer_name=~\"$importer\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Current retries",
   "type": "gauge",
   "description": "The number of attempts to replay failed transactions.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_importer_retries_total{namespace=\"$cluster\",importer_name=~\"$importer\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Details (importer = $importer)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All transactions by procedure name",
     "type": "bargauge",
     "description": "The number of import transactions that succeeded.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (procedure_name) (increase(voltdb_importer_success_total{namespace=\"$cluster\",host_name=~\"$host\",importer_name=~\"$importer\"}[$__range]))",
       "legendFormat": "{{procname}}"
      }
     ]
    },
    {
     "title": "All failed transactions by procedure name",
     "type": "bargauge",
     "description": "The number of import transactions that failed.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (procedure_name) (increase(voltdb_importer_failure_total{namespace=\"$cluster\",host_name=~\"$host\",importer_name=~\"$importer\"}[$__range]))",
       "legendFormat": "{{procname}}"
      }
     ]
    },
    {
     "title": "Successful transactions rate by host",
     "type": "timeseries",
     "description": "The number of import transactions that succeeded.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host_name) (rate(voltdb_importer_success_total{namespace=\"$cluster\",host_name=~\"$host\",importer_name=~\"$importer\"}[$__rate_interval]))",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Failed transactions rate by host",
     "type": "timeseries",
     "description": "The number of import transactions that failed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host_name) (rate(voltdb_importer_failure_total{namespace=\"$cluster\",host_name=~\"$host\",importer_name=~\"$importer\"}[$__rate_interval]))",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Successful transactions by procedure",
     "type": "timeseries",
     "description": "The number of import transactions that succeeded.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (procedure_name) (rate(voltdb_importer_success_total{namespace=\"$cluster\",host_name=~\"$host\",importer_name=~\"$importer\"}[$__rate_interval]))",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Failed transactions by procedure",
     "type": "timeseries",
     "description": "The number of import transactions that failed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (procedure_name) (rate(voltdb_importer_failure_total{namespace=\"$cluster\",host_name=~\"$host\",importer_name=~\"$importer\"}[$__rate_interval]))",
       "legendFormat": "{{source}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Procedures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Most invoked procedures",
     "type": "table",
     "description": "The number of import transactions that succeeded.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (procedure_name)\n(\n    increase(voltdb_importer_success_total\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n    }[$__range])\n)",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Top procedure invocation times ($procedure)",
     "type": "timeseries",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(\n    max by (procedure_name)\n    (\n        voltdb_procedure_invoked_time_seconds_max\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            procedure_name=~\"$procedure\"\n    \n        }\n    )\n)",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Execution times distribution ($procedure)",
     "type": "heatmap",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(voltdb_procedure_invoked_time_seconds_bucket\n{\n    namespace=\"$cluster\",\n    host_name=~\"$host\",\n    procedure_name=~\"$procedure\"\n}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}