{
 "title": "VoltDB Procedures",
 "tags": [
  "voltdb",
  "procedures"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({namespace=\"$cluster\",host_name=~\"$host\"},site_id)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},partition_id)"
    }
   },
   {
    "name": "procedure",
    "label": "Procedure",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},procedure_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Procedures Overview (Rate Errors Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Procedure invocation rate",
   "type": "stat",
   "description": "The number of procedure invocation per 5 minutes, also includes procedures being replicated into partition replicas, so it does not equal the number of transactions issued by clients",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\n(\n    rate\n    (\n        voltdb_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Number of transactions executed by the connected clients",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\n(\n    rate\n    (\n        voltdb_initiator_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "stat",
   "description": "The number of times the procedure failed unexpectedly.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        voltdb_procedure_failed_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Abort rate",
   "type": "stat",
   "description": "The number of times the procedure was aborted.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        voltdb_procedure_aborted_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Worst case time",
   "type": "stat",
   "description": "The length of time it took to execute the stored procedure.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\"\n    }\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Procedures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total procedures invocation counts",
     "type": "timeseries",
     "description": "The number of procedure invocation per 5 minutes, also includes procedures being replicated into partition replicas, so it does not equal the number of transactions issued by clients",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    rate(\n        voltdb_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"\n        }[$__rate_interval]\n    )\n)",
       "legendFormat": "procedures / total"
      }
     ]
    },
    {
     "title": "Total transactions counts",
     "type": "timeseries",
     "description": "Number of transactions executed by the connected clients",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    rate(\n        voltdb_initiator_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            procedure_name=~\"$procedure\",\n            connection_origin=\"EXTERNAL\"\n        }[$__rate_interval]\n))",
       "legendFormat": "procedures / total"
      }
     ]
    },
    {
     "title": "Procedures invocation rate ($procedure)",
     "type": "timeseries",
     "description": "The total number of invocations of this procedure at this site.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (procedure_name) (\n    rate(\n        voltdb_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"\n        }[$__rate_interval]\n    )\n)",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Transactions per procedure rate ($procedure)",
     "type": "timeseries",
     "description": "The number of times the stored procedure has been invoked by this connection on this host node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (procedure_name) (rate(\n        voltdb_initiator_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            procedure_name=~\"$procedure\",\n            connection_origin=\"EXTERNAL\"\n        }[$__rate_interval]\n))",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Execution times distribution ($procedure)",
     "type": "heatmap",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(voltdb_procedure_invoked_time_seconds_bucket\n{\n    namespace=\"$cluster\",\n    host_name=~\"$host\",\n    partition_id=~\"$partition\",\n    procedure_name=~\"$procedure\"\n}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Top procedure invocation times ($procedure)",
     "type": "timeseries",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort(\n    max by (procedure_name)\n    (\n        voltdb_procedure_invoked_time_seconds_max\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"\n        }\n    )\n)",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Hottest procedures ($procedure)",
     "type": "table",
     "description": "The total number of invocations of this procedure at this site.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (procedure_name)\n(\n    increase(voltdb_procedure_invoked_total\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }[$__range])\n)",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Slowest procedures ($procedure)",
     "type": "table",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (procedure_name)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Top procedure invocation counts ($procedure)",
     "type": "timeseries",
     "description": "The total number of invocations of this procedure at this site.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sort(\n    max by (procedure_name)\n    (\n        rate(voltdb_procedure_invoked_total\n        {\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"\n        }[$__rate_interval])\n    )\n)",
       "legendFormat": "{{procedure_name}}"
      }
     ]
    },
    {
     "title": "Average result size ($procedure)",
     "type": "timeseries",
     "description": "The total size of the results returned by the procedure.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(voltdb_procedure_result_size_bytes{\n            namespace=\"$cluster\",\n            host_name=~\"$host\",\n            partition_id=~\"$partition\",\n            procedure_name=~\"$procedure\"}\n [$__rate_interval]))",
       "legendFormat": "Avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution time matrices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Procedures x Hostame execution time matrix ($procedure) - size proportional to time",
     "type": "marcusolsson-treemap-panel",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (procedure_name, host_name)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
       "legendFormat": "{{host_name}} / {{procedure_name}}"
      }
     ]
    },
    {
     "title": "Procedures x Hostame execution time matrix ($procedure)",
     "type": "table",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (procedure_name, host_name)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Procedures x Partition execution time matrix ($procedure)",
     "type": "table",
     "description": "The length of time it took to execute the stored procedure.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (procedure_name, partition_id)\n(\n    voltdb_procedure_invoked_time_seconds_max\n    {\n        namespace=\"$cluster\",\n        host_name=~\"$host\",\n        partition_id=~\"$partition\",\n        procedure_name=~\"$procedure\"\n    }\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster internal latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worst case time spent in inbound queue",
     "type": "stat",
     "description": "The distribution of the time tasks were waiting in the queue for the execution on the remote node, initiated by this connection.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(\n    voltdb_io_network_inbound_queue_time_seconds_max {\n        namespace=\"$cluster\",\n        host_name=~\"$host\"\n    }\n)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Worst case task execution (RTT)",
     "type": "stat",
     "description": "The distribution of the time taken to receive acknowledgment of the execution of the stored procedures on the leader node, initiated by this connection.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max (\n    voltdb_io_network_procedure_round_trip_time_seconds_max {\n        namespace=\"$cluster\",\n        host_name=~\"$host\"\n    }\n)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Worst case task replication (RTT)",
     "type": "stat",
     "description": "The distribution of the time it took to receive acknowledgment from the replica.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max (\n    voltdb_io_network_replication_round_trip_time_seconds_max {\n        namespace=\"$cluster\",\n        host_name=~\"$host\"\n    }\n)",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Replication latency (RTT)",
     "type": "table",
     "description": "The distribution of the time it took to receive acknowledgment from the replica.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (\n    voltdb_io_network_replication_round_trip_time_seconds_max {\n        namespace=\"$cluster\"\n    }\n) by (host_name, connection_hostname)",
       "legendFormat": "{{connection_hostname}}"
      }
     ]
    }
   ]
  }
 ]
}