{
 "title": "VoltDB Export",
 "tags": [
  "voltdb",
  "export"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},partition_id)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\",partition_id=~\"$partition\"},table_name)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\",partition_id=~\"$partition\", table_name=~\"$table\"},export_target)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\",partition_id=~\"$partition\", table_name=~\"$table\", export_target=~\"$target\"},export_source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total tuples sent",
   "type": "stat",
   "description": "The total number of records queued to the export target since the queue was created.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(voltdb_export_tuple_count_total{namespace=\"$cluster\",host_name=~\"$host\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total missing tuples",
   "type": "stat",
   "description": "The number of records missing from the queue for the current stream and partition.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_queue_gap_total{namespace=\"$cluster\",host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Pending tuples",
   "type": "stat",
   "description": "The number of records still waiting to be written to or acknowledged by the target.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_tuple_pending_total{namespace=\"$cluster\",host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max export latency",
   "type": "stat",
   "description": "The distribution of time between when records are inserted, and then acknowledged by the target.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_export_latency_seconds_max{namespace=\"$cluster\",host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Active export streams",
   "type": "stat",
   "description": "Informational metric that contains metadata. Tags: EXPORT_IS_ACTIVE - \"True\" if is enabled and not blocked and is master. EXPORT_STATUS - The current status of the export connection. \"Active\" - Queue is currently exporting to the target; \"Blocked\" - There is a gap in the queue and export is waiting to see if the missing records become available when a missing node rejoins; \"Dropped\" - either the source stream has been dropped from the schema or the export configuration has been removed from the configuration and queue is draining any remaining records.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (partition_id) (voltdb_export_info{namespace=\"$cluster\",host_name=~\"$host\",export_is_active=\"TRUE\"})"
    }
   ]
  },
  {
   "title": "Inactive export streams",
   "type": "stat",
   "description": "Informational metric that contains metadata. Tags: EXPORT_IS_ACTIVE - \"True\" if is enabled and not blocked and is master. EXPORT_STATUS - The current status of the export connection. \"Active\" - Queue is currently exporting to the target; \"Blocked\" - There is a gap in the queue and export is waiting to see if the missing records become available when a missing node rejoins; \"Dropped\" - either the source stream has been dropped from the schema or the export configuration has been removed from the configuration and queue is draining any remaining records.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (partition_id) (voltdb_export_info{namespace=\"$cluster\",host_name=~\"$host\",export_is_active=\"FALSE\"})"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pending tuples count by source and partition",
     "type": "marcusolsson-treemap-panel",
     "description": "The number of records still waiting to be written to or acknowledged by the target.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (partition_id, export_source) (voltdb_export_tuple_pending_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",export_source=~\"$source\", export_target=~\"$target\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending tuples count by partition and target",
     "type": "marcusolsson-treemap-panel",
     "description": "The number of records still waiting to be written to or acknowledged by the target.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (partition_id, export_target) (voltdb_export_tuple_pending_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",export_source=~\"$source\", export_target=~\"$target\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last acknowledged tuple (max for each partition)",
     "type": "table",
     "description": "The timestamp when the last tuple was acknowledged as received by the target.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (partition_id) \n  (\n    time() * 1000 \n    - (\n        voltdb_export_last_acked_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",export_source=~\"$source\", export_target=~\"$target\"} > 0\n      )\n  )\n  /1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last acknowledged tuple (max for each source)",
     "type": "table",
     "description": "The timestamp when the last tuple was acknowledged as received by the target.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (export_source) \n  (\n    time() * 1000\n    - (\n        voltdb_export_last_acked_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",export_source=~\"$source\", export_target=~\"$target\"} > 0\n      )\n  )\n  /1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending tuples by source",
     "type": "timeseries",
     "description": "The number of records still waiting to be written to or acknowledged by the target.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (export_source) (voltdb_export_tuple_pending_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",export_source=~\"$source\", export_target=~\"$target\"})",
       "legendFormat": "{{export_source}}"
      }
     ]
    },
    {
     "title": "Missing tuples by source",
     "type": "timeseries",
     "description": "The number of records missing from the queue for the current stream and partition.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (export_source) (voltdb_export_queue_gap_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",export_source=~\"$source\", export_target=~\"$target\"})",
       "legendFormat": "{{export_source}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Export activity timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Export timeline",
     "type": "state-timeline",
     "description": "Informational metric that contains metadata. Tags: EXPORT_IS_ACTIVE - \"True\" if is enabled and not blocked and is master. EXPORT_STATUS - The current status of the export connection. \"Active\" - Queue is currently exporting to the target; \"Blocked\" - There is a gap in the queue and export is waiting to see if the missing records become available when a missing node rejoins; \"Dropped\" - either the source stream has been dropped from the schema or the export configuration has been removed from the configuration and queue is draining any remaining records.",
     "gridPos": { "h": 27, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "group by (host_name, export_is_active, export_target) (voltdb_export_info{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",export_source=~\"$source\", export_target=~\"$target\", export_is_active=~\".+\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}