{
 "title": "Volt cluster overview",
 "tags": [
  "voltdb",
  "voltactivedata"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values({job=~\"$job\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of Traffic on Entire Volt Cluster",
   "type": "stat",
   "description": "Transactions per second served by the entire Volt cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (voltdb_latency_tps{job=~\"$job\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Volt CPU Utilisation",
   "type": "gauge",
   "description": "Volt process CPU utilisation average of each node. can display all nodes or particular node selected in Hostname option. The time interval for average calculations will be the dashboard interval selected. ",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(voltdb_cpu_usage_percent{hostname=~\"$hostname\", job=~\"$job\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Volt RAM Utilisation",
   "type": "gauge",
   "description": "RAM memory utilisation average of each node. can display all nodes or particular node selected in Hostname option. The time interval for average calculations will be the dashboard interval selected. ",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(voltdb_memory_rss_bytes{hostname=~\"$hostname\", job=~\"$job\"}[$__interval]) / on(hostname, job) avg_over_time(voltdb_memory_physicalmemory_bytes{hostname=~\"$hostname\", job=~\"$job\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Volt JAVA heap Utilisation",
   "type": "gauge",
   "description": "Volt JAVA heap memory utilisation average of each node. can display all nodes or particular node selected in Hostname option. The time interval for average calculations will be the dashboard interval selected. ",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(voltdb_memory_javaused_bytes{hostname=~\"$hostname\", job=~\"$job\"}[$__interval]) / on(hostname, job) avg_over_time(voltdb_memory_javamaxheap_bytes{hostname=~\"$hostname\", job=~\"$job\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Current CommandLog Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(voltdb_commandlog_outstanding_txns{hostname=~\"$hostname\", job=~\"$job\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Max Latency 99th percentile ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(voltdb_latency_99th_seconds{hostname=~\"$hostname\", job=~\"$job\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "p99.9 Latency",
   "type": "stat",
   "description": "99.9 percentile latency per node. ",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(voltdb_latency_three_nines_seconds{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Procedure Failures",
   "type": "stat",
   "description": "Any Failures in the cluster",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(voltdb_procedure_failures{hostname=~\"$Node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Procedure Aborts",
   "type": "stat",
   "description": "Any Aborts in the cluster",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "voltdb_procedure_aborts{hostname=~\"$Node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Cluster Details : historic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput ",
   "type": "timeseries",
   "description": "Transactions per second on VoltDB Cluster, and per node breakdown",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (voltdb_latency_tps{hostname=~\"$hostname\", job=~\"$job\"})",
     "legendFormat": "Cluster TPS"
    },
    {
     "expr": "voltdb_latency_tps{hostname=~\"$hostname\", job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Cluster Latency Details Avg across all nodes",
   "type": "timeseries",
   "description": "Average Latency Graph across all nodes",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (voltdb_latency_99th_seconds {job=~\"$job\"} )",
     "legendFormat": "99pct "
    }
   ]
  },
  {
   "title": "Max latency (whole Volt path)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(hostname)(voltdb_latency_max_seconds{hostname=~\"$hostname\", job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Latency Details - Per node",
   "type": "timeseries",
   "description": "Detailed Latency Graph in milliseconds",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "voltdb_latency_99th_seconds {hostname=~\"$hostname\" , job=~\"$job\"} ",
     "legendFormat": "99pct - {{hostname}}"
    }
   ]
  },
  {
   "title": "Max execution time for Procedures",
   "type": "timeseries",
   "description": "Maximum time taken to execute procedures",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (procedure) (voltdb_procedure_max_execution_time_seconds{hostname=~\"$hostname\", job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Procedure Invocation Rate",
   "type": "timeseries",
   "description": "Rate of procedure invocation ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (procedure) (voltdb_procedure_invocations {hostname=~\"$hostname\",job=~\"$job\"})",
     "legendFormat": "Count {{procedure}} {{hostname}}"
    }
   ]
  },
  {
   "title": "Procedure Failure and Abort Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (procedure) (voltdb_procedure_failures {hostname=~\"$hostname\",job=~\"$job\"})",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum by (procedure) (voltdb_procedure_aborts {hostname=~\"$hostname\",job=~\"$job\"})",
     "legendFormat": "Aborts"
    }
   ]
  },
  {
   "title": "Hottest Procedure by invocation ",
   "type": "table",
   "description": "Hottest Procedure by invocation ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (procedure,job) (voltdb_procedure_invocations{hostname=~\"$hostname\", job=~\"$job\"})",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Slowest Procedure (max execution time)",
   "type": "table",
   "description": "slowest Procedure by execution time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (procedure)(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$hostname\"})",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "RAM % Utilisation ",
   "type": "timeseries",
   "description": "Time series of RAM utilisation on each node",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(voltdb_memory_rss_bytes{hostname=~\"$hostname\", job=~\"$job\"}[$__interval]) / on(hostname, job) avg_over_time(voltdb_memory_physicalmemory_bytes{hostname=~\"$hostname\", job=~\"$job\"}[$__interval]) ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU % Utilisation Volt Process",
   "type": "timeseries",
   "description": "Timeseries CPU volt process utilisation",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "voltdb_cpu_usage_percent {hostname=~\"$hostname\",job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "JVM details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": " GC Old gen Count ($hostname)",
   "type": "timeseries",
   "description": " GC Old gen Count per node",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (hostname, job) (voltdb_gc_oldgen_gc_count {job=~\"$job\", hostname=~\"$hostname\"}) ",
     "legendFormat": "GC olden Time taken - {{hostname}}"
    }
   ]
  },
  {
   "title": " GC New gen count($hostname)",
   "type": "timeseries",
   "description": " GC New gen Avg time per node",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (hostname, job) (voltdb_gc_newgen_gc_count {job=~\"$job\", hostname=~\"$hostname\"}) ",
     "legendFormat": "GC newGen Time taken - {{hostname}}"
    }
   ]
  },
  {
   "title": " GC Old gen Avg time ($hostname)",
   "type": "timeseries",
   "description": " GC Old gen Avg time per node",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (hostname, job) (voltdb_gc_oldgen_avg_gc_time_seconds {job=~\"$job\", hostname=~\"$hostname\"}) ",
     "legendFormat": "GC olden Time taken - {{hostname}}"
    }
   ]
  },
  {
   "title": " GC New gen Avg time ($hostname)",
   "type": "timeseries",
   "description": " GC New gen Avg time per node",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (hostname, job) (voltdb_gc_newgen_avg_gc_time_seconds {job=~\"$job\", hostname=~\"$hostname\"}) ",
     "legendFormat": "GC newGen Time taken - {{hostname}}"
    }
   ]
  },
  {
   "title": "RSS memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "voltdb_memory_rss_bytes {hostname=~\"$hostname\", job=~\"$job\"} ",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum (voltdb_memory_rss_bytes {hostname=~\"$hostname\", job=~\"$job\"} )",
     "legendFormat": "Total Cluster RSS"
    }
   ]
  },
  {
   "title": "Total physical memory ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (hostname) (voltdb_memory_physicalmemory_bytes{hostname=~\"$hostname\", job=~\"$job\"}) ",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum (voltdb_memory_physicalmemory_bytes {hostname=~\"$hostname\", job=~\"$job\"} )",
     "legendFormat": "Total Cluster Physical memory"
    }
   ]
  },
  { "title": "Queue Depth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Queue Depth Site Wise",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "voltdb_queue_depth {hostname=~\"$hostname\", job=~\"$job\"}",
     "legendFormat": "SiteID: {{siteid}} Hostname: {{hostname}}"
    }
   ]
  },
  {
   "title": "Queue Depth Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum (voltdb_queue_depth {hostname=~\"$hostname\", job=~\"$job\"})",
     "legendFormat": "queue Depth Cluster"
    }
   ]
  },
  {
   "title": "Commandlog Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Outstanding Command log Transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "voltdb_commandlog_outstanding_txns {hostname=~\"$hostname\",job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Fsync interval ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "voltdb_commandlog_fsync_interval_seconds {hostname=~\"$hostname\", job=~\"$job\"} ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Connections and Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Unfinished transactions Volt knows about",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cnxhostname) (voltdb_liveclients_outstanding_txns{job=~\"$job\",hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished transactions Volt is about to send back to clients",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cnxhostname) (voltdb_liveclients_outstanding_reponse_messages{job=~\"$job\",hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}