{
 "title": "Volt Procedures",
 "tags": [
  "voltdb",
  "procedures",
  "voltactivedata"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\"},partitionid)"
    }
   },
   {
    "name": "procedure",
    "label": "Procedure",
    "query": {
     "query": "label_values({job=~\"$job\", hostname=~\"$host\",partitionid=~\"$partition\"}, procedure)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Procedures Overview (Rate Errors Duration)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocation rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\"}[$__interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_procedure_failures{job=~\"$job\",hostname=~\"$host\"}[$__interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Abort rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(voltdb_procedure_aborts{job=~\"$job\",hostname=~\"$host\"}[$__interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Worst case time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$host\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Procedures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Procedures invocation counts ($procedure)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"}[$__interval]))",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Hottest procedures ($procedure)",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (procedure)(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"})",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "Top procedure invocation counts ($procedure)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(max by (procedure)(increase(voltdb_procedure_invocations{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"}[$__interval])))",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Top procedure invocation times ($procedure)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(max by (procedure)(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"}))",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Slowest procedures ($procedure)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure)(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"})",
     "legendFormat": "{{procname}}"
    }
   ]
  },
  {
   "title": "Average result size distribution ($procedure)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "voltdb_procedure_avg_result_size_bytes{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"}",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Average execution times distribution ($procedure)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "voltdb_procedure_avg_execution_time_seconds{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"}",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Execution time matrices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Procedures x Hostame execution time matrix ($procedure) - size proportional to time",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure, hostname)(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"})"
    },
    { "expr": "1" }
   ]
  },
  {
   "title": "Procedures x Hostame execution time matrix ($procedure)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure, hostname)(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"})"
    }
   ]
  },
  {
   "title": "Procedures x Partition execution time matrix ($procedure)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (procedure, partitionid)(voltdb_procedure_max_execution_time_seconds{job=~\"$job\",hostname=~\"$host\",partitionid=~\"$partition\",procedure=~\"$procedure\"})"
    }
   ]
  }
 ]
}