{
 "title": "VoltDB Tables",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},table_name)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\", table_name=~\"$table\"},partition_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tables Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Table allocated memory",
   "type": "stat",
   "description": "The amount of memory allocated for the storage of database records (including free space).",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_memory_tupleallocated_bytes{namespace=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuple count",
   "type": "stat",
   "description": "The number of rows stored for this table in the current partition. For streams, the cumulative total number of rows inserted into the stream.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_table_tuple_total{namespace=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index memory usage",
   "type": "stat",
   "description": "The estimated amount of memory consumed by the index entries.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_index_memory_estimate_bytes{namespace=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of index entries",
   "type": "stat",
   "description": "The number of index entries in the partition.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_index_entry_count_total{namespace=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table $table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table sizes ($table)",
     "type": "timeseries",
     "description": "The total size of memory allocated for storing inline data associated with this table in this partition. For streams, the amount of memory in use to queue export data (both in memory and as export overflow) prior to its being passed to the export target.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(table_name)(voltdb_memory_tupleallocated_bytes{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"})",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Table Compaction ($table)",
     "type": "timeseries",
     "description": "- `voltdb_compaction_execution_seconds`: The amount of time it took for compaction to complete.\n- `voltdb_compaction_relocated_total`: The number of tuples relocated during compaction.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(voltdb_compaction_execution_seconds_bucket{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"}[5m])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(voltdb_compaction_relocated_total_bucket{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"}[5m])) by (le))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(voltdb_compaction_execution_seconds_bucket{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\",table_name=~\"$table\"}[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tuple count: table by partition (table == $table, partition == $partition)",
     "type": "marcusolsson-treemap-panel",
     "description": "The number of rows stored for this table in the current partition. For streams, the cumulative total number of rows inserted into the stream.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (table_name, partition_id) (voltdb_table_tuple_total{namespace=\"$cluster\",host_name=~\"$host\",table_name=~\"$table\",partition_id=~\"$partition\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hosts by partitions",
     "type": "marcusolsson-treemap-panel",
     "description": "The number of rows stored for this table in the current partition. For streams, the cumulative total number of rows inserted into the stream.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host_name, partition_id)(voltdb_table_tuple_total{namespace=\"$cluster\",host_name=~\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Index name by partition matrix (table == $table, partition == $partition)",
     "type": "marcusolsson-treemap-panel",
     "description": "The number of index entries in the partition.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (index_name, partition_id)(voltdb_index_entry_count_total{namespace=\"$cluster\",host_name=~\"$host\",table_name=~\"$table\",partition_id=~\"$partition\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}