{
 "title": "VoltDB XDCR",
 "tags": [
  "voltdb",
  "xdcr",
  "dr"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},host_name)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", host_name=~\"$host\"},partition_id)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Producer overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replication lag",
   "type": "gauge",
   "description": "Time it took to receive acknowledgement from the consumer.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_dr_producer_round_trip_time_seconds_max{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffers usage",
   "type": "gauge",
   "description": "Average number of bytes waiting to be sent to the consumer",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_dr_producer_partition_available_to_send_total_bytes{namespace=\"$cluster\",host_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Size of data queued for transmission to the customer",
   "type": "bargauge",
   "description": "The total number of bytes currently queued for transmission to the consumer vs. currently held in memory.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_producer_partition_queued_in_memory_total_bytes{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(voltdb_dr_producer_partition_queued_total_bytes{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "Memory+disk"
    }
   ]
  },
  {
   "title": "Queue gap",
   "type": "stat",
   "description": "The number of missing transactions between those already acknowledged by the consumer and the next available for transmission.",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_dr_producer_partition_queue_gap_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection status to other clusters",
   "type": "piechart",
   "description": "Informational metric. Tags: DR_STREAM_TYPE - The type of stream, which can either be \"Transactions\" or \"Snapshot\". DR_LAST_QUEUED_ID - The ID of the last transaction queued for transmission to the consumer. DR_LAST_ACK_ID - The ID of the last transaction acknowledged by the consumer. DR_IS_SYNCED - Indicates whether the database is currently being replicated. If replication has not started, or the overflow capacity has been exceeded (that is, replication has failed), the value of ISSYNCED is \"false\". If replication is currently in progress, the value is \"true\". DR_MODE - Indicates whether this particular partition is replicating data to the consumer (\"NOrmal\") or not (\"Paused\"). Only one copy of each logical partition actually sends data during replication. So for clusters with a K-safety value greater than zero, not all physical partitions will report \"Normal\" even when replication is in progress. DR_CONNECTION_STATUS - Indicates whether the connection to the consumer is operational (\"UP\") or not (\"DOWN\"). CONSUMER_LIMIT_TYPE - The type of limit on the DR queue. The response is either BYTES or BUFFERS. CURRENT_DR_PROTOCOL - The DR protocol version currently in use when sending data to consumers. SUPPORTED_DR_PROTOCOL - The highest version of DR protocol this cluster is capable of using to send data to consumers.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_producer_partition_info{namespace=\"$cluster\",dr_connection_status=\"UP\"})",
     "legendFormat": "up"
    },
    {
     "expr": "sum(voltdb_dr_producer_partition_info{namespace=\"$cluster\",dr_connection_status=\"DOWN\"})",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Last acknowledged transaction",
   "type": "stat",
   "description": "The timestamp of the last transaction acknowledged by the consumer.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(voltdb_dr_producer_partition_last_ack_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks queued for transmission to the replica(s)",
   "type": "stat",
   "description": "The number of DR tasks waiting to be processed.",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_producer_node_tasks_queue_depth_total{namespace=\"$cluster\", host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Producer details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Buffers waiting for ACK (partition)",
   "type": "bargauge",
   "description": "The total number of buffers in this partition waiting for acknowledgement from the consumer.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(voltdb_dr_producer_partition_buffers_waiting_for_ack_total{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\"}) by (partition_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data queued for transmission (host/partition)",
   "type": "marcusolsson-treemap-panel",
   "description": "The total number of bytes currently queued for transmission to the consumer.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_name, partition_id) (voltdb_dr_producer_partition_queued_total_bytes{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The timestamp of the last transaction queued for transmission to the consumer (per host, per partition)",
   "type": "table",
   "description": "The timestamp of the last transaction queued for transmission to the consumer.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by (host_name, partition_id) (voltdb_dr_producer_partition_last_queued_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer queue occupation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "DR queue occupation by consumer & producer ($host)",
     "type": "barchart",
     "description": "Comparison of the number of free bytes left in the DR queue and the number of bytes waiting to be sent to the consumer.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(voltdb_dr_consumer_partition_available_buffer_bytes_bytes{namespace=\"$cluster\",host_name=~\"$host\"}) by (host_id, partition_id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(voltdb_dr_producer_partition_available_to_send_total_bytes{namespace=\"$cluster\",host_name=~\"$host\"}) by (host_id, partition_id)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Consumer overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Avarage replication speed",
   "type": "gauge",
   "description": "Total number of bytes this consumer received.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_dr_consumer_bytes_replicated_bytes{namespace=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffers usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_consumer_partition_available_buffer_bytes_bytes{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicated buffers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_consumer_partition_duplicate_buffers_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ignored buffers",
   "type": "gauge",
   "description": "The number of buffers received but dropped because the queue was full.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_consumer_partition_ignored_buffers_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Limit type(s)",
   "type": "stat",
   "description": "Tags: IS_COVERED - Boolean value indicating whether this partition is currently connected to and receiving data from a matching partition on the producer cluster. COVERING_HOST - The host name of the server in the producer cluster that is providing DR data to this partition. If IS_COVERED is \"false\", this label is empty. IS_PAUSED - Boolean indicating whether this partition is paused. A partition \"pauses\" when the schema of the DR tables on the producer change to no longer match the consumer and all binary logs prior to the change have been processed. CONSUMER_LIMIT_TYPE - The type of limit on the DR queue. The response is either BYTES or BUFFERS. LAST_APPLIED_DR_PROTOCOL - The current DR protocol version of binary logs being received and applied for this partition.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "voltdb_dr_consumer_partition_info{namespace=\"$cluster\", host_name=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last received transaction",
   "type": "stat",
   "description": "The timestamp of the last transaction received from the producer.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_dr_consumer_partition_last_received_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Rate of replication",
   "type": "timeseries",
   "description": "Total number of bytes this consumer received.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(voltdb_dr_consumer_bytes_replicated_bytes{namespace=\"$cluster\",host_name=~\"$host\"}[$__rate_interval])) by (host_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicated buffers",
   "type": "timeseries",
   "description": "Exponentially weighted moving average rate of replication over the past minute.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(voltdb_dr_consumer_partition_duplicate_buffers_total{namespace=\"$cluster\",host_name=~\"$host\"}[$__rate_interval])) by (host_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The received timestamp",
   "type": "table",
   "description": "The timestamp of the last received transaction.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "max by (host_name, partition_id) (voltdb_dr_consumer_partition_last_received_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\",partition_id=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duplicated buffers",
   "type": "stat",
   "description": "Exponentially weighted moving average rate of replication over the past minute.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_consumer_partition_duplicate_buffers_total{namespace=\"$cluster\",host_name=~\"$host\"}) by (host_name, partition_id)",
     "legendFormat": "{{host_name}} [{{partition_id}}]"
    }
   ]
  },
  { "title": "Conflicts overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Last conflict",
   "type": "stat",
   "description": "The timestamp of the last conflict.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * max(voltdb_dr_last_conflict_timestamp_seconds{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All conflicts count",
   "type": "stat",
   "description": "The total number of conflicts that have been recorded for this table in this partition.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_conflicts_count_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Divergences due to conflicts",
   "type": "stat",
   "description": "The number of conflicts that may have resulted in divergence between the clusters, which is a subset of the total conflicts.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_divergence_count_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Constraint violations",
   "type": "stat",
   "description": "The number of constraint violation conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_constraint_violation_count_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing rows",
   "type": "stat",
   "description": "The number of missing row conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_missing_row_count_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mismatches",
   "type": "stat",
   "description": "The number of missing row conflicts that occurred.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_dr_row_timestamp_mismatch_count_total{namespace=\"$cluster\",host_name=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Conflict details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Conflicts by type (host = $host, partition = $partition)",
   "type": "timeseries",
   "description": "- `voltdb_dr_constraint_violation_count_total`: The number of constraint violation conflicts that occurred.\n- `voltdb_dr_divergence_count_total`: The number of conflicts that may have resulted in divergence between the clusters, which is a subset of the total conflicts.\n- `voltdb_dr_missing_row_count_total`: The number of missing row conflicts that occurred.\n- `voltdb_dr_row_timestamp_mismatch_count_total`: The number of timestamp mismatch conflicts that occurred.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(voltdb_dr_constraint_violation_count_total{namespace=\"$cluster\",host_name=~\"$host\", partition_id=~\"$partition\"})",
     "legendFormat": "constraint violations"
    },
    {
     "expr": "sum(voltdb_dr_divergence_count_total{namespace=\"$cluster\",host_name=~\"$host\", partition_id=~\"$partition\"})",
     "legendFormat": "divergences"
    },
    {
     "expr": "sum(voltdb_dr_missing_row_count_total{namespace=\"$cluster\",host_name=~\"$host\", partition_id=~\"$partition\"})",
     "legendFormat": "missing rows"
    },
    {
     "expr": "sum(voltdb_dr_row_timestamp_mismatch_count_total{namespace=\"$cluster\",host_name=~\"$host\", partition_id=~\"$partition\"})",
     "legendFormat": "mismatches"
    }
   ]
  },
  {
   "title": "Conflicts by table (host = $host, partition = $partition)",
   "type": "marcusolsson-treemap-panel",
   "description": "- `voltdb_dr_constraint_violation_count_total`: The number of constraint violation conflicts that occurred.\n- `voltdb_dr_missing_row_count_total`: The number of missing row conflicts that occurred.\n- `voltdb_dr_row_timestamp_mismatch_count_total`: The number of timestamp mismatch conflicts that occurred.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "expr": "sum by (table_name,__name__ ) ({__name__=~\"voltdb_dr_constraint_violation_count_total|voltdb_dr_missing_row_count_total|voltdb_dr_row_timestamp_mismatch_count_total\", namespace=\"$cluster\",host_name=~\"$host\", partition_id=~\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Divergences by table (host = $host, partition = $partition)",
   "type": "timeseries",
   "description": "The number of conflicts that may have resulted in divergence between the clusters, which is a subset of the total conflicts.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "expr": "sum by (table_name) (voltdb_dr_divergence_count_total{namespace=\"$cluster\",host_name=~\"$host\", partition_id=~\"$partition\"})",
     "legendFormat": "divergences - {{table_name}}"
    }
   ]
  },
  { "title": "Replication RTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "RTT ($cluster)",
   "type": "timeseries",
   "description": "The distribution of time it took to receive acknowledgement from the consumer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(voltdb_dr_producer_partition_round_trip_time_seconds_sum{namespace=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{host_name}}[{{partition_id}}]"
    },
    {
     "expr": "max(voltdb_dr_producer_partition_round_trip_time_seconds_max{namespace=\"$cluster\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RTT ($cluster)",
   "type": "heatmap",
   "description": "The distribution of time it took to receive acknowledgement from the consumer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "avg (voltdb_dr_producer_partition_round_trip_time_seconds_bucket{namespace=\"$cluster\"}) by (partition_id, host_id)",
     "legendFormat": "{{partition_id}}"
    }
   ]
  }
 ]
}