{
 "title": "VoltDB Export",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\"},partitionid)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\",partitionid=~\"$partition\"}, source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending tuples",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_export_pending_tuples_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Total queued tuples",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(voltdb_export_total_queued_tuples_count{namespace=\"$cluster\",hostname=~\"$host\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total missing tuples",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_export_missing_tuples_count{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Max export latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_export_max_latency_seconds{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Pending tuples count by source and partition",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source, partitionid) (voltdb_export_pending_tuples_count{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\",source=~\"$source\"})"
    }
   ]
  },
  {
   "title": "Missing tuples count by source and partition",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source, partitionid) (voltdb_export_missing_tuples_count)"
    }
   ]
  },
  {
   "title": "Acknowledgements lag (max across partitions)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (partitionid) (voltdb_export_last_acked_timestamp)",
     "legendFormat": "{{partitionid}}"
    }
   ]
  },
  {
   "title": "Acknowledgements lag (max across sources)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (source) (voltdb_export_last_acked_timestamp)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Pending tuples count by source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (voltdb_export_pending_tuples_count)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Missing tuples count by source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (voltdb_export_missing_tuples_count)",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}