{
 "title": "VoltDB XDCR Two Way",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster1", "label": "Cluster 1", "query": { "query": "label_values(namespace)" } },
   { "name": "cluster2", "label": "Cluster 2", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\"},partitionid)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values({namespace=\"$cluster\", hostname=~\"$host\",partitionid=~\"$partition\"}, source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Producer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Size of pending tuples",
   "type": "gauge",
   "description": "The total number of bytes currently queued for transmission\nto the replica.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drproducer_total_queued_bytes{namespace=\"$cluster1\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Memory queues size",
   "type": "gauge",
   "description": "The total number of bytes of queued data currently held\nin memory. If the amount of total bytes is larger than the\namount in memory, the remainder is kept in overflow storage on disk.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drproducer_total_queued_in_memory_bytes{namespace=\"$cluster1\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Bytes available to consume",
   "type": "gauge",
   "description": "The number of bytes waiting to be sent to the consumer",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drproducer_consumer_available_bytes{namespace=\"$cluster1\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Last acknowledged transaction",
   "type": "stat",
   "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(voltdb_drproducer_last_acked_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\"}* 1000)"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "gauge",
   "description": "The timestamp of the last transaction acknowledged by the\nconsumer.",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdb_drproducer_last_acked_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\"}-voltdb_drproducer_last_queued_timestamp_seconds{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Consumer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average replication speed",
   "type": "gauge",
   "description": "The total number of bytes currently queued for transmission\nto the replica.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_drconsumer_1min_avg_replication_bytes_per_second{namespace=\"$cluster\",hostname=~\"$host\"})"
    },
    {}
   ]
  },
  {
   "title": "Available bytes",
   "type": "gauge",
   "description": "The total number of bytes currently queued for transmission\nto the replica.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_drconsumer_available_bytes{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Duplicated buffers",
   "type": "gauge",
   "description": "The number of repeated buffers received after the initial\npackets were dropped because the queue was full.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(voltdb_drconsumer_duplicate_buffers{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Ignored buffers",
   "type": "gauge",
   "description": "The number of buffers received but dropped because the\nqueue was full.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(voltdb_drconsumer_ignored_buffers{namespace=\"$cluster\",hostname=~\"$host\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Replication speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg (voltdb_drconsumer_1min_avg_replication_bytes_per_second{namespace=\"$cluster\",hostname=~\"$host\",partitionid=~\"$partition\",source=~\"$source\"})"
    },
    { "expr": "voltdb_drconsumer_" }
   ]
  }
 ]
}