{
 "title": "VoltDB Configuration",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(namespace)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({namespace=\"$cluster\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# VoltDB configuration\n\nBelow's information comes from @SystemInformation call, for detailed description please go to [documentation](https://docs.voltdb.com/UsingVoltDB/sysprocsysteminfo.php#sysprocsysinforetvalovervw)."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Volt Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (voltdb_systeminformation_overview_host_info{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{dummy}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()*1000) - voltdb_systeminformation_overview_cluster{namespace=\"$cluster\",hostname=~\"$host\", property=\"starttime\"}"
    }
   ]
  },
  {
   "title": "Cluster state",
   "type": "stat",
   "description": "INITIALIZING, RUNNING, PAUSED, SHUTTINGDOWN",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (clusterstate) (voltdb_systeminformation_overview_cluster_info{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{dummy}}"
    }
   ]
  },
  {
   "title": "Cluster safety ",
   "type": "stat",
   "description": "REDUCED/FULL",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (clustersafety) (voltdb_systeminformation_overview_cluster_info{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{dummy}}"
    }
   ]
  },
  {
   "title": "Cluster id",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (clusterid) (voltdb_systeminformation_overview_cluster_info{namespace=\"$cluster\",hostname=~\"$host\"})",
     "legendFormat": "{{dummy}}"
    }
   ]
  },
  {
   "title": "Full cluster size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_overview_cluster{namespace=\"$cluster\",hostname=~\"$host\", property=\"fullclustersize\"}"
    }
   ]
  },
  {
   "title": "Current cluster size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_overview_cluster{namespace=\"$cluster\",hostname=~\"$host\", property=\"currentclustersize\"}"
    }
   ]
  },
  {
   "title": "Overview configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max (voltdb_systeminformation_overview_cluster_info{namespace=\"$cluster\",hostname=~\"$host\"}) by (kubernetes,replicationrole)"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_overview_cluster{namespace=\"$cluster\",hostname=~\"$host\", property=\"cpucores\"}"
    }
   ]
  },
  {
   "title": "CPU threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_overview_cluster{namespace=\"$cluster\",hostname=~\"$host\", property=\"cputhreads\"}"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Deployment configuration",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max (voltdb_systeminformation_deployment_info{namespace=\"$cluster\",hostname=~\"$host\"}) by (drpriority,prioritiesenabled,drrole,elasticduration,elasticthroughput,export,heartbeattimeout,partitiondetection,temptablesmaxsize)"
    }
   ]
  },
  {
   "title": "Command log configuration",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "max (voltdb_systeminformation_commandlog_info{namespace=\"$cluster\",hostname=~\"$host\"}) by (commandlogenabled, commandlogfreqtime, commandlogfreqtxns, commandlogmode)"
    }
   ]
  },
  {
   "title": "K factor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_deployment{namespace=\"$cluster\",hostname=~\"$host\", property=\"sitesperhost\"}"
    }
   ]
  },
  {
   "title": "Snapshot configuration",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "max (voltdb_systeminformation_snapshot_info{namespace=\"$cluster\",hostname=~\"$host\"}) by (snapshotenabled, snapshotfrequency, snapshotpriority, snapshotretain)"
    }
   ]
  },
  {
   "title": "Sites per host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_deployment{namespace=\"$cluster\",hostname=~\"$host\", property=\"sitesperhost\"}"
    }
   ]
  },
  { "title": "License", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "License information",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max (voltdb_systeminformation_license_info{namespace=\"$cluster\",hostname=~\"$host\"}) by (features_commandlogging, features_dractiveactive, features_drreplication, features_trial)"
    }
   ]
  },
  {
   "title": "License expires in",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_license{namespace=\"$cluster\",hostname=~\"$host\", property=\"expiration\"} - (time()*1000)"
    }
   ]
  },
  {
   "title": "License expires on",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "time: YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_license{namespace=\"$cluster\",hostname=~\"$host\", property=\"expiration\"}"
    }
   ]
  },
  {
   "title": "Host count max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_license{namespace=\"$cluster\",hostname=~\"$host\", property=\"hostcount_max\"}"
    }
   ]
  },
  {
   "title": "Core count max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdb_systeminformation_license{namespace=\"$cluster\",hostname=~\"$host\", property=\"corecount_max\"}"
    }
   ]
  }
 ]
}